In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

ruta = "informacion_delictiva_del_municipio_bucaramanga.csv"

df = pd.read_csv(ruta, sep=",")

In [3]:
# 1. Conocer los datos

print(df.shape) # columnas y filas

(130202, 26)

In [4]:
df.info() #tipos de datos, nulos y memoria

<class 'pandas.DataFrame'>
RangeIndex: 130202 entries, 0 to 130201
Data columns (total 26 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   DESCRIPCION_CONDUCTA  130202 non-null  str
 1   ARMAS_MEDIOS          130202 non-null  str
 2   BARRIOS_HECHO         130202 non-null  str
 3   FECHA_HECHO           130202 non-null  str
 4   HORA_HECHO            130202 non-null  str
 5   EDAD                  130202 non-null  str
 6   SEXO                  130202 non-null  str
 7   MOVIL_VICTIMA         130202 non-null  str
 8   MOVIL_AGRESOR         130202 non-null  str
 9   CLASE_SITIO           130202 non-null  str
 10  ARTICULO              130202 non-null  str
 11  DELITO_SOLO           130202 non-null  str
 12  CURSO_VIDA            130202 non-null  str
 13  CURSO_VIDA_ORDEN      130202 non-null  int64
 14  AÑO_NUM               130202 non-null  int64
 15  MES_NUM               130202 non-null  int64
 16  DIA_NUM               130202 non-null  int64
 17  RANGO_HORARIO         130202 non-null  str
 18  TIPOLOGÍA             130202 non-null  str
 19  RANGO_HORARIO_ORDEN   130202 non-null  int64
 20  DIA_NOMBRE            130202 non-null  str
 21  DIA_NOMBRE_ORDEN      130202 non-null  int64
 22  LOCALIDAD             130202 non-null  str
 23  NUM_COM               130202 non-null  int64
 24  NOM_COM               130202 non-null  str
 25  CANTIDAD_UNICA        130202 non-null  int64
dtypes: int64(8), str(18)
memory usage: 25.8 MB

In [5]:
display(df.head()) #primeras 5 filas

,DESCRIPCION_CONDUCTA,ARMAS_MEDIOS,BARRIOS_HECHO,FECHA_HECHO,HORA_HECHO,EDAD,SEXO,MOVIL_VICTIMA,MOVIL_AGRESOR,CLASE_SITIO,...,DIA_NUM,RANGO_HORARIO,TIPOLOGÍA,RANGO_HORARIO_ORDEN,DIA_NOMBRE,DIA_NOMBRE_ORDEN,LOCALIDAD,NUM_COM,NOM_COM,CANTIDAD_UNICA
0,ARTÍCULO 111. LESIONES PERSONALES,ARMA BLANCA / CORTOPUNZANTE,TRANSICIÓN,2016-01-01,20:00:00,54,MASCULINO,CONDUCTOR TAXI,A PIE,VIAS PUBLICAS,...,1,20:00-20:59,DELITOS CONTRA LA VIDA Y LA INTEGRIDAD PERSONAL,20,viernes,5,02. NORORIENTAL,2,NORORIENTAL,1
1,ARTÍCULO 111. LESIONES PERSONALES,ARMA BLANCA / CORTOPUNZANTE,ESTORAQUES I Y II,2016-01-01,20:00:00,27,MASCULINO,A PIE,A PIE,CANCHA DE FUTBOL,...,1,20:00-20:59,DELITOS CONTRA LA VIDA Y LA INTEGRIDAD PERSONAL,20,viernes,5,17. MUTIS,17,MUTIS,1
2,ARTÍCULO 111. LESIONES PERSONALES,ARMA BLANCA / CORTOPUNZANTE,LA CONCORDIA,2016-01-01,20:00:00,24,FEMENINO,A PIE,A PIE,OFICINAS,...,1,20:00-20:59,DELITOS CONTRA LA VIDA Y LA INTEGRIDAD PERSONAL,20,viernes,5,06. LA CONCORDIA,6,LA CONCORDIA,1
3,ARTÍCULO 111. LESIONES PERSONALES,ARMA BLANCA / CORTOPUNZANTE,LA AURORA,2016-01-01,02:00:00,19,FEMENINO,A PIE,A PIE,FRENTE A DISCOTECAS,...,1,2:00-2:59,DELITOS CONTRA LA VIDA Y LA INTEGRIDAD PERSONAL,2,viernes,5,13. ORIENTAL,13,ORIENTAL,1
4,ARTÍCULO 111. LESIONES PERSONALES,ARMA BLANCA / CORTOPUNZANTE,SAN RAFAEL,2016-01-01,16:15:00,25,FEMENINO,A PIE,A PIE,FRENTE A RESIDENCIAS - VIA PUBLICA,...,1,16:00-16:59,DELITOS CONTRA LA VIDA Y LA INTEGRIDAD PERSONAL,16,viernes,5,03. SAN FRANCISCO,3,SAN FRANCISCO,1

In [6]:
display(df.sample(5))

,DESCRIPCION_CONDUCTA,ARMAS_MEDIOS,BARRIOS_HECHO,FECHA_HECHO,HORA_HECHO,EDAD,SEXO,MOVIL_VICTIMA,MOVIL_AGRESOR,CLASE_SITIO,...,DIA_NUM,RANGO_HORARIO,TIPOLOGÍA,RANGO_HORARIO_ORDEN,DIA_NOMBRE,DIA_NOMBRE_ORDEN,LOCALIDAD,NUM_COM,NOM_COM,CANTIDAD_UNICA
91947,ARTÍCULO 229. VIOLENCIA INTRAFAMILIAR,CONTUNDENTES,SAN FRANCISCO,2023-03-21,13:00:00,41,FEMENINO,NO DISPONIBLE,A PIE,VIAS PUBLICAS,...,21,13:00-13:59,DELITOS CONTRA LA FAMILIA,13,martes,2,03. SAN FRANCISCO,3,SAN FRANCISCO,1
10858,ARTÍCULO 111. LESIONES PERSONALES,ARMA BLANCA / CORTOPUNZANTE,COLORADOS,2017-01-04,20:30:00,15,MASCULINO,A PIE,CONDUCTOR MOTOCICLETA,DENTRO DE LA VIVIENDA,...,4,20:00-20:59,DELITOS CONTRA LA VIDA Y LA INTEGRIDAD PERSONAL,20,miércoles,3,01. NORTE,1,NORTE,1
55946,ARTÍCULO 239. HURTO PERSONAS,ARMA DE FUEGO,CABECERA DEL LLANO,2020-11-13,20:00:00,22,MASCULINO,A PIE,A PIE,PARQUES,...,13,20:00-20:59,DELITOS CONTRA EL PATRIMONIO ECONOMICO,20,viernes,5,12. CABECERA DEL LLANO,12,CABECERA DEL LLANO,1
60525,ARTÍCULO 239. HURTO ENTIDADES COMERCIALES,SIN EMPLEO DE ARMAS,CABECERA DEL LLANO,2021-03-16,18:45:00,NO DISPONIBLE,NO DISPONIBLE,A PIE,A PIE,LOCAL COMERCIAL,...,16,18:00-18:59,DELITOS CONTRA EL PATRIMONIO ECONOMICO,18,martes,2,12. CABECERA DEL LLANO,12,CABECERA DEL LLANO,1
42525,ARTÍCULO 239. HURTO ENTIDADES COMERCIALES,SIN EMPLEO DE ARMAS,MIRAFLORES,2019-09-01,09:00:00,NO DISPONIBLE,NO DISPONIBLE,A PIE,A PIE,ESTABLECIMIENTO DE COMERCIO,...,1,9:00-9:59,DELITOS CONTRA EL PATRIMONIO ECONOMICO,9,domingo,7,14. MORRORICO,14,MORRORICO,1

In [8]:
print(df.describe(include="all").T)

                         count unique                                     top  \
DESCRIPCION_CONDUCTA    130202     44            ARTÍCULO 239. HURTO PERSONAS
ARMAS_MEDIOS            130202     40                     SIN EMPLEO DE ARMAS
BARRIOS_HECHO           130202    410                                  CENTRO
FECHA_HECHO             130202   3743                              2023-09-09
HORA_HECHO              130202   1422                                10:00:00
EDAD                    130202     98                           NO DISPONIBLE
SEXO                    130202      3                                FEMENINO
MOVIL_VICTIMA           130202     14                                   A PIE
MOVIL_AGRESOR           130202     15                                   A PIE
CLASE_SITIO             130202    232                           VIAS PUBLICAS
ARTICULO                130202     34                            ARTÍCULO 239
DELITO_SOLO             130202     44                          HURTO PERSONAS
CURSO_VIDA              130202     19                           NO DISPONIBLE
CURSO_VIDA_ORDEN      130202.0    NaN                                     NaN
AÑO_NUM               130202.0    NaN                                     NaN
MES_NUM               130202.0    NaN                                     NaN
DIA_NUM               130202.0    NaN                                     NaN
RANGO_HORARIO           130202     24                             10:00-10:59
TIPOLOGÍA               130202      5  DELITOS CONTRA EL PATRIMONIO ECONOMICO
RANGO_HORARIO_ORDEN   130202.0    NaN                                     NaN
DIA_NOMBRE              130202      7                                  sábado
DIA_NOMBRE_ORDEN      130202.0    NaN                                     NaN
LOCALIDAD               130202     23                            13. ORIENTAL
NUM_COM               130202.0    NaN                                     NaN
NOM_COM                 130202     23                                ORIENTAL
CANTIDAD_UNICA        130202.0    NaN                                     NaN

                       freq         mean       std     min     25%     50%  \
DESCRIPCION_CONDUCTA  60869          NaN       NaN     NaN     NaN     NaN
ARMAS_MEDIOS          64731          NaN       NaN     NaN     NaN     NaN
BARRIOS_HECHO         10780          NaN       NaN     NaN     NaN     NaN
FECHA_HECHO              86          NaN       NaN     NaN     NaN     NaN
HORA_HECHO             4864          NaN       NaN     NaN     NaN     NaN
EDAD                  32966          NaN       NaN     NaN     NaN     NaN
SEXO                  61227          NaN       NaN     NaN     NaN     NaN
MOVIL_VICTIMA         90192          NaN       NaN     NaN     NaN     NaN
MOVIL_AGRESOR         98590          NaN       NaN     NaN     NaN     NaN
CLASE_SITIO           72255          NaN       NaN     NaN     NaN     NaN
ARTICULO              79985          NaN       NaN     NaN     NaN     NaN
DELITO_SOLO           60869          NaN       NaN     NaN     NaN     NaN
CURSO_VIDA            32967          NaN       NaN     NaN     NaN     NaN
CURSO_VIDA_ORDEN        NaN     9.433772   5.61155     0.0     5.0     7.0
AÑO_NUM                 NaN  2020.765464  2.827225  2016.0  2018.0  2021.0
MES_NUM                 NaN     6.487228  3.478339     1.0     3.0     7.0
DIA_NUM                 NaN    15.596135  8.816359     1.0     8.0    16.0
RANGO_HORARIO          8694          NaN       NaN     NaN     NaN     NaN
TIPOLOGÍA             80689          NaN       NaN     NaN     NaN     NaN
RANGO_HORARIO_ORDEN     NaN    12.414663  6.414697     0.0     8.0    13.0
DIA_NOMBRE            20929          NaN       NaN     NaN     NaN     NaN
DIA_NOMBRE_ORDEN        NaN     4.020461  1.980379     1.0     2.0     4.0
LOCALIDAD             15822          NaN       NaN     NaN     NaN     NaN
NUM_COM                 NaN     8.663408  5.193705     1.0     4.0     9.0
NOM_COM               15822          NaN       NaN     NaN     NaN     NaN
CANTIDAD_UNICA          NaN     1.000038  0.006197     1.0     1.0     1.0

                         75%     max
DESCRIPCION_CONDUCTA     NaN     NaN
ARMAS_MEDIOS             NaN     NaN
BARRIOS_HECHO            NaN     NaN
FECHA_HECHO              NaN     NaN
HORA_HECHO               NaN     NaN
EDAD                     NaN     NaN
SEXO                     NaN     NaN
MOVIL_VICTIMA            NaN     NaN
MOVIL_AGRESOR            NaN     NaN
CLASE_SITIO              NaN     NaN
ARTICULO                 NaN     NaN
DELITO_SOLO              NaN     NaN
CURSO_VIDA               NaN     NaN
CURSO_VIDA_ORDEN        18.0    18.0
AÑO_NUM               2023.0  2026.0
MES_NUM                 10.0    12.0
DIA_NUM                 23.0    31.0
RANGO_HORARIO            NaN     NaN
TIPOLOGÍA                NaN     NaN
RANGO_HORARIO_ORDEN     18.0    23.0
DIA_NOMBRE               NaN     NaN
DIA_NOMBRE_ORDEN         6.0     7.0
LOCALIDAD                NaN     NaN
NUM_COM                 13.0    21.0
NOM_COM                  NaN     NaN
CANTIDAD_UNICA           1.0     2.0

In [9]:
print(df.describe())

       CURSO_VIDA_ORDEN        AÑO_NUM        MES_NUM        DIA_NUM  \
count     130202.000000  130202.000000  130202.000000  130202.000000
mean           9.433772    2020.765464       6.487228      15.596135
std            5.611550       2.827225       3.478339       8.816359
min            0.000000    2016.000000       1.000000       1.000000
25%            5.000000    2018.000000       3.000000       8.000000
50%            7.000000    2021.000000       7.000000      16.000000
75%           18.000000    2023.000000      10.000000      23.000000
max           18.000000    2026.000000      12.000000      31.000000

       RANGO_HORARIO_ORDEN  DIA_NOMBRE_ORDEN        NUM_COM  CANTIDAD_UNICA
count        130202.000000     130202.000000  130202.000000   130202.000000
mean             12.414663          4.020461       8.663408        1.000038
std               6.414697          1.980379       5.193705        0.006197
min               0.000000          1.000000       1.000000        1.000000
25%               8.000000          2.000000       4.000000        1.000000
50%              13.000000          4.000000       9.000000        1.000000
75%              18.000000          6.000000      13.000000        1.000000
max              23.000000          7.000000      21.000000        2.000000

In [10]:
# 2.Revisar calidad

display(df.isna().sum().sort_values(ascending=False))
print("Duplicados: ", df.duplicated().sum())

DESCRIPCION_CONDUCTA    0
ARMAS_MEDIOS            0
BARRIOS_HECHO           0
FECHA_HECHO             0
HORA_HECHO              0
EDAD                    0
SEXO                    0
MOVIL_VICTIMA           0
MOVIL_AGRESOR           0
CLASE_SITIO             0
ARTICULO                0
DELITO_SOLO             0
CURSO_VIDA              0
CURSO_VIDA_ORDEN        0
AÑO_NUM                 0
MES_NUM                 0
DIA_NUM                 0
RANGO_HORARIO           0
TIPOLOGÍA               0
RANGO_HORARIO_ORDEN     0
DIA_NOMBRE              0
DIA_NOMBRE_ORDEN        0
LOCALIDAD               0
NUM_COM                 0
NOM_COM                 0
CANTIDAD_UNICA          0
dtype: int64

Duplicados:  219

In [11]:
# trabajar siempre desde una copia

df_limpio = df.copy()

df_limpio.columns = (
    df_limpio.columns.str.strip()
    .str.lower()
    .str.replace(r"\s+", "_", regex=True)
)

In [12]:
#Quitar espacios y uniformar texto

columnas_texto = df_limpio.select_dtypes(include="object").columns
df_limpio[columnas_texto] = df_limpio[columnas_texto].apply(
    lambda col: col.str.strip().str.upper()
)

C:\Users\andre\AppData\Local\Temp\ipykernel_173092\3861346460.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  columnas_texto = df_limpio.select_dtypes(include="object").columns

In [13]:
#ver todos los nombres de columnas
df.columns.tolist()

['DESCRIPCION_CONDUCTA',
 'ARMAS_MEDIOS',
 'BARRIOS_HECHO',
 'FECHA_HECHO',
 'HORA_HECHO',
 'EDAD',
 'SEXO',
 'MOVIL_VICTIMA',
 'MOVIL_AGRESOR',
 'CLASE_SITIO',
 'ARTICULO',
 'DELITO_SOLO',
 'CURSO_VIDA',
 'CURSO_VIDA_ORDEN',
 'AÑO_NUM',
 'MES_NUM',
 'DIA_NUM',
 'RANGO_HORARIO',
 'TIPOLOGÍA',
 'RANGO_HORARIO_ORDEN',
 'DIA_NOMBRE',
 'DIA_NOMBRE_ORDEN',
 'LOCALIDAD',
 'NUM_COM',
 'NOM_COM',
 'CANTIDAD_UNICA']

In [14]:
#Nulos por columna 
nulos = df.isna().sum().sort_values(ascending=False)
display(nulos[nulos > 0])

Series([], dtype: int64)

In [15]:
# Porcentaje de nulos: ayuda a decidir después
porcentaje_nulos = (df.isna().mean() * 100).sort_values(ascending=False)
display(porcentaje_nulos[porcentaje_nulos > 0].round(2))

Series([], dtype: float64)

In [16]:
# Filas completamente duplicadas
print("Filas duplicadas:", df.duplicated().sum())

Filas duplicadas: 219

In [17]:
duplicados = df[df.duplicated(keep=False)]
display(duplicados.head(10))

,DESCRIPCION_CONDUCTA,ARMAS_MEDIOS,BARRIOS_HECHO,FECHA_HECHO,HORA_HECHO,EDAD,SEXO,MOVIL_VICTIMA,MOVIL_AGRESOR,CLASE_SITIO,...,DIA_NUM,RANGO_HORARIO,TIPOLOGÍA,RANGO_HORARIO_ORDEN,DIA_NOMBRE,DIA_NOMBRE_ORDEN,LOCALIDAD,NUM_COM,NOM_COM,CANTIDAD_UNICA
74138,ARTÍCULO 239. HURTO MOTOCICLETAS,LLAVE MAESTRA,DIAMANTE II,2022-02-01,07:15:00,NO DISPONIBLE,NO DISPONIBLE,A PIE,CONDUCTOR MOTOCICLETA,PARQUEADERO,...,1,7:00-7:59,DELITOS CONTRA EL PATRIMONIO ECONOMICO,7,martes,2,10. PROVENZA,10,PROVENZA,1
74139,ARTÍCULO 239. HURTO MOTOCICLETAS,LLAVE MAESTRA,DIAMANTE II,2022-02-01,07:15:00,NO DISPONIBLE,NO DISPONIBLE,A PIE,CONDUCTOR MOTOCICLETA,PARQUEADERO,...,1,7:00-7:59,DELITOS CONTRA EL PATRIMONIO ECONOMICO,7,martes,2,10. PROVENZA,10,PROVENZA,1
75749,ARTÍCULO 120. LESIONES CULPOSAS ( EN ACCIDENTE...,VEHICULO,KENNEDY,2022-03-11,07:40:00,16,FEMENINO,CONDUCTOR MOTOCICLETA,CONDUCTOR VEHICULO,VIAS PUBLICAS,...,11,7:00-7:59,DELITOS CONTRA LA VIDA Y LA INTEGRIDAD PERSONAL,7,viernes,5,01. NORTE,1,NORTE,1
75750,ARTÍCULO 120. LESIONES CULPOSAS ( EN ACCIDENTE...,VEHICULO,KENNEDY,2022-03-11,07:40:00,16,FEMENINO,CONDUCTOR MOTOCICLETA,CONDUCTOR VEHICULO,VIAS PUBLICAS,...,11,7:00-7:59,DELITOS CONTRA LA VIDA Y LA INTEGRIDAD PERSONAL,7,viernes,5,01. NORTE,1,NORTE,1
78802,ARTÍCULO 239. HURTO PERSONAS,SIN EMPLEO DE ARMAS,GIRARDOT,2022-05-20,10:00:00,22,FEMENINO,A PIE,A PIE,DISCOTECAS,...,20,10:00-10:59,DELITOS CONTRA EL PATRIMONIO ECONOMICO,10,viernes,5,04. OCCIDENTAL,4,OCCIDENTAL,1
78803,ARTÍCULO 239. HURTO PERSONAS,SIN EMPLEO DE ARMAS,GIRARDOT,2022-05-20,10:00:00,22,FEMENINO,A PIE,A PIE,DISCOTECAS,...,20,10:00-10:59,DELITOS CONTRA EL PATRIMONIO ECONOMICO,10,viernes,5,04. OCCIDENTAL,4,OCCIDENTAL,1
79189,ARTÍCULO 111. LESIONES PERSONALES,CONTUNDENTES,UNIVERSIDAD,2022-05-31,19:00:00,28,FEMENINO,A PIE,A PIE,VIAS PUBLICAS,...,31,19:00-19:59,DELITOS CONTRA LA VIDA Y LA INTEGRIDAD PERSONAL,19,martes,2,03. SAN FRANCISCO,3,SAN FRANCISCO,1
79190,ARTÍCULO 111. LESIONES PERSONALES,CONTUNDENTES,UNIVERSIDAD,2022-05-31,19:00:00,28,FEMENINO,A PIE,A PIE,VIAS PUBLICAS,...,31,19:00-19:59,DELITOS CONTRA LA VIDA Y LA INTEGRIDAD PERSONAL,19,martes,2,03. SAN FRANCISCO,3,SAN FRANCISCO,1
80486,ARTÍCULO 239. HURTO PERSONAS,SIN EMPLEO DE ARMAS,CIUDADELA REAL DE MINAS,2022-07-02,22:00:00,19,FEMENINO,A PIE,CONDUCTOR MOTOCICLETA,VIAS PUBLICAS,...,2,22:00-22:59,DELITOS CONTRA EL PATRIMONIO ECONOMICO,22,sábado,6,07. LA CIUDADELA,7,LA CIUDADELA,1
80487,ARTÍCULO 239. HURTO PERSONAS,SIN EMPLEO DE ARMAS,CIUDADELA REAL DE MINAS,2022-07-02,22:00:00,19,FEMENINO,A PIE,CONDUCTOR MOTOCICLETA,VIAS PUBLICAS,...,2,22:00-22:59,DELITOS CONTRA EL PATRIMONIO ECONOMICO,22,sábado,6,07. LA CIUDADELA,7,LA CIUDADELA,1

In [18]:
#valores distintos por columna 
df.nunique().sort_values()

CANTIDAD_UNICA             2
SEXO                       3
TIPOLOGÍA                  5
DIA_NOMBRE_ORDEN           7
DIA_NOMBRE                 7
AÑO_NUM                   11
MES_NUM                   12
MOVIL_VICTIMA             14
MOVIL_AGRESOR             15
CURSO_VIDA_ORDEN          19
CURSO_VIDA                19
NUM_COM                   21
LOCALIDAD                 23
NOM_COM                   23
RANGO_HORARIO             24
RANGO_HORARIO_ORDEN       24
DIA_NUM                   31
ARTICULO                  34
ARMAS_MEDIOS              40
DESCRIPCION_CONDUCTA      44
DELITO_SOLO               44
EDAD                      98
CLASE_SITIO              232
BARRIOS_HECHO            410
HORA_HECHO              1422
FECHA_HECHO             3743
dtype: int64