In [46]:
import pandas as pd

ruta = "titanic.csv"


datos_titanic = pd.read_csv(ruta, sep=",")

In [47]:
print(datos_titanic)

     Survived  Pclass                                               Name  \
0           0       3                             Mr. Owen Harris Braund
1           1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...
2           1       3                              Miss. Laina Heikkinen
3           1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle
4           0       3                            Mr. William Henry Allen
..        ...     ...                                                ...
882         0       2                               Rev. Juozas Montvila
883         1       1                        Miss. Margaret Edith Graham
884         0       3                     Miss. Catherine Helen Johnston
885         1       1                               Mr. Karl Howell Behr
886         0       3                                 Mr. Patrick Dooley

        Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare
0      male  22.0                        1                        0   7.2500
1    female  38.0                        1                        0  71.2833
2    female  26.0                        0                        0   7.9250
3    female  35.0                        1                        0  53.1000
4      male  35.0                        0                        0   8.0500
..      ...   ...                      ...                      ...      ...
882    male  27.0                        0                        0  13.0000
883  female  19.0                        0                        0  30.0000
884  female   7.0                        1                        2  23.4500
885    male  26.0                        0                        0  30.0000
886    male  32.0                        0                        0   7.7500

[887 rows x 8 columns]

In [3]:
display(datos_titanic.head())

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500

In [48]:
datos_titanic.columns.tolist()

['Survived',
 'Pclass',
 'Name',
 'Sex',
 'Age',
 'Siblings/Spouses Aboard',
 'Parents/Children Aboard',
 'Fare']

In [49]:
datos_titanic.describe()

,Survived,Pclass,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
count,887.000000,887.000000,887.000000,887.000000,887.000000,887.00000
mean,0.385569,2.305524,29.471443,0.525366,0.383315,32.30542
std,0.487004,0.836662,14.121908,1.104669,0.807466,49.78204
min,0.000000,1.000000,0.420000,0.000000,0.000000,0.00000
25%,0.000000,2.000000,20.250000,0.000000,0.000000,7.92500
50%,0.000000,3.000000,28.000000,0.000000,0.000000,14.45420
75%,1.000000,3.000000,38.000000,1.000000,0.000000,31.13750
max,1.000000,3.000000,80.000000,8.000000,6.000000,512.32920

In [50]:
#agregar una nueva columna

datos_titanic["supervivientes"] = datos_titanic["Survived"].map({0: "Fallecido", 1: "Superviviente"})

In [51]:
print(datos_titanic)

     Survived  Pclass                                               Name  \
0           0       3                             Mr. Owen Harris Braund
1           1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...
2           1       3                              Miss. Laina Heikkinen
3           1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle
4           0       3                            Mr. William Henry Allen
..        ...     ...                                                ...
882         0       2                               Rev. Juozas Montvila
883         1       1                        Miss. Margaret Edith Graham
884         0       3                     Miss. Catherine Helen Johnston
885         1       1                               Mr. Karl Howell Behr
886         0       3                                 Mr. Patrick Dooley

        Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  \
0      male  22.0                        1                        0   7.2500
1    female  38.0                        1                        0  71.2833
2    female  26.0                        0                        0   7.9250
3    female  35.0                        1                        0  53.1000
4      male  35.0                        0                        0   8.0500
..      ...   ...                      ...                      ...      ...
882    male  27.0                        0                        0  13.0000
883  female  19.0                        0                        0  30.0000
884  female   7.0                        1                        2  23.4500
885    male  26.0                        0                        0  30.0000
886    male  32.0                        0                        0   7.7500

    supervivientes
0        Fallecido
1    Superviviente
2    Superviviente
3    Superviviente
4        Fallecido
..             ...
882      Fallecido
883  Superviviente
884      Fallecido
885  Superviviente
886      Fallecido

[887 rows x 9 columns]

In [8]:
print(datos_titanic.describe())

         Survived      Pclass         Age  Siblings/Spouses Aboard  \
count  887.000000  887.000000  887.000000               887.000000
mean     0.385569    2.305524   29.471443                 0.525366
std      0.487004    0.836662   14.121908                 1.104669
min      0.000000    1.000000    0.420000                 0.000000
25%      0.000000    2.000000   20.250000                 0.000000
50%      0.000000    3.000000   28.000000                 0.000000
75%      1.000000    3.000000   38.000000                 1.000000
max      1.000000    3.000000   80.000000                 8.000000

       Parents/Children Aboard       Fare
count               887.000000  887.00000
mean                  0.383315   32.30542
std                   0.807466   49.78204
min                   0.000000    0.00000
25%                   0.000000    7.92500
50%                   0.000000   14.45420
75%                   0.000000   31.13750
max                   6.000000  512.32920

In [52]:
print(f"\nDimensiones: {datos_titanic.shape[0]} filas y {datos_titanic.shape[1]} columnas")

Dimensiones: 887 filas y 9 columnas

In [53]:
datos_titanic["supervivientes"].value_counts()

supervivientes
Fallecido        545
Superviviente    342
Name: count, dtype: int64

In [54]:
print(datos_titanic.describe().T)

                         count       mean        std   min     25%      50%  \
Survived                 887.0   0.385569   0.487004  0.00   0.000   0.0000
Pclass                   887.0   2.305524   0.836662  1.00   2.000   3.0000
Age                      887.0  29.471443  14.121908  0.42  20.250  28.0000
Siblings/Spouses Aboard  887.0   0.525366   1.104669  0.00   0.000   0.0000
Parents/Children Aboard  887.0   0.383315   0.807466  0.00   0.000   0.0000
Fare                     887.0  32.305420  49.782040  0.00   7.925  14.4542

                             75%       max
Survived                  1.0000    1.0000
Pclass                    3.0000    3.0000
Age                      38.0000   80.0000
Siblings/Spouses Aboard   1.0000    8.0000
Parents/Children Aboard   0.0000    6.0000
Fare                     31.1375  512.3292

In [24]:
print(datos_titanic.columns.tolist())

['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'Siblings/Spouses Aboard', 'Parents/Children Aboard', 'Fare', 'supervivientes']

In [26]:
display(datos_titanic.head())

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare,supervivientes
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500,Fallecido
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833,Superviviente
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250,Superviviente
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000,Superviviente
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500,Fallecido

In [55]:
#funciones

def en_mayusculas(x): 
    return x.upper()

datos_titanic["Nombres pasajeros"] = datos_titanic["Name"].map(en_mayusculas)

In [56]:
display(datos_titanic.head())

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare,supervivientes,Nombres pasajeros
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500,Fallecido,MR. OWEN HARRIS BRAUND
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833,Superviviente,MRS. JOHN BRADLEY (FLORENCE BRIGGS THAYER) CUM...
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250,Superviviente,MISS. LAINA HEIKKINEN
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000,Superviviente,MRS. JACQUES HEATH (LILY MAY PEEL) FUTRELLE
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500,Fallecido,MR. WILLIAM HENRY ALLEN

In [57]:
datos_titanic = datos_titanic.rename(columns={'supervivientes': 'Supervivientes'})

In [59]:
en_mayusculas = lambda x : x.upper() if type(x) == str else x

In [60]:
datos_titanic = datos_titanic.map(en_mayusculas)
display(datos_titanic)

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare,Supervivientes,Nombres pasajeros
0,0,3,MR. OWEN HARRIS BRAUND,MALE,22.0,1,0,7.2500,FALLECIDO,MR. OWEN HARRIS BRAUND
1,1,1,MRS. JOHN BRADLEY (FLORENCE BRIGGS THAYER) CUM...,FEMALE,38.0,1,0,71.2833,SUPERVIVIENTE,MRS. JOHN BRADLEY (FLORENCE BRIGGS THAYER) CUM...
2,1,3,MISS. LAINA HEIKKINEN,FEMALE,26.0,0,0,7.9250,SUPERVIVIENTE,MISS. LAINA HEIKKINEN
3,1,1,MRS. JACQUES HEATH (LILY MAY PEEL) FUTRELLE,FEMALE,35.0,1,0,53.1000,SUPERVIVIENTE,MRS. JACQUES HEATH (LILY MAY PEEL) FUTRELLE
4,0,3,MR. WILLIAM HENRY ALLEN,MALE,35.0,0,0,8.0500,FALLECIDO,MR. WILLIAM HENRY ALLEN
...,...,...,...,...,...,...,...,...,...,...
882,0,2,REV. JUOZAS MONTVILA,MALE,27.0,0,0,13.0000,FALLECIDO,REV. JUOZAS MONTVILA
883,1,1,MISS. MARGARET EDITH GRAHAM,FEMALE,19.0,0,0,30.0000,SUPERVIVIENTE,MISS. MARGARET EDITH GRAHAM
884,0,3,MISS. CATHERINE HELEN JOHNSTON,FEMALE,7.0,1,2,23.4500,FALLECIDO,MISS. CATHERINE HELEN JOHNSTON
885,1,1,MR. KARL HOWELL BEHR,MALE,26.0,0,0,30.0000,SUPERVIVIENTE,MR. KARL HOWELL BEHR
886,0,3,MR. PATRICK DOOLEY,MALE,32.0,0,0,7.7500,FALLECIDO,MR. PATRICK DOOLEY